### ISSUE TITLE
put pubspec file in the example

### ISSUE THREAD

**Issue by shinriyo** [funwithflutter/flutter_confetti#12]
there are no `pubspec.yml` in the example folder

I gusess someone can't test easily.

```
cd example
flutter create .
```

and,  put below in dependencies section
```
  confetti:
    path: ../
```
and move `example/main.dart` to `example/lib/main.dart`

It is good.

**Comment by nadavfima** [comment]
@shinriyo I was wondering how I could test the changes I made... thanks!
