### ISSUE TITLE
Custom particles

### ISSUE THREAD

**Issue by ueman** [funwithflutter/flutter_confetti#18]
It would be nice if one could specify a custom widget which should be painted as confetti.

**Comment by shinriyo** [comment]
I agree with you

**Comment by funwithflutter** [comment]
The confetti are being painted in a CustomPainter, so no widgets are being painted. The package draws rectangles in the CustomPainter's paint method and updates the rectangles positions each frame.
Could maybe add an option to add a custom path or rectangle.

**Comment by EArminjon** [comment]
could be great  :)

**Comment by DeepStyles** [comment]
can i draw image or text replacing tht rectangle in painter???

**Comment by funwithflutter** [comment]
There is now an optional `createParticlePath` argument where you can specify your own path to create any shape you want :)

Closed in #39
