### ISSUE TITLE
Support orientation changes

### ISSUE THREAD

**Issue by alexandereverett92** [funwithflutter/flutter_confetti#23]
Currently if you start the confetti in portrait and switch to landscape the right side of the screen is cut off and gets no confetti.

The size calculation is only done on init, should be possible to re-run this on orientation change, possibly using the OrientationBuilder 
https://api.flutter.dev/flutter/widgets/OrientationBuilder-class.html

**Comment by funwithflutter** [comment]
Thanks for noticing this. The package is now updated. I didn't use OrientationBuilder. Instead updated the package in such a way that it will update on any layout change. For example, on web or desktop if you resize the window then the screen restrictions and confetti positions are updated.

Please let me know if this has resolved your issue and then I will close the issue.

**Comment by funwithflutter** [comment]
Closing the issue.
