### ISSUE TITLE
Can't get it to play first time

### ISSUE THREAD

**Issue by amigax** [funwithflutter/flutter_confetti#35]
For me it only plays if I do a hot reload, it does not play when I visit the screen in my app for first time - Im not sure why this is, any ideas?

**Comment by amigax** [comment]
actually looks like it was due to being in a Future.delayed, not sure why that impacts it but no big deal really

**Comment by funwithflutter** [comment]
Okay can I go ahead and close this issue ? :)

**Comment by amigax** [comment]
yes thanks ;)
