### ISSUE TITLE
This widget has been unmounted, so the State no longer has a context (and should be considered defunct).

### ISSUE THREAD

**Issue by idootop** [funwithflutter/flutter_confetti#36]
![图片](https://user-images.githubusercontent.com/35302658/101252966-45f17080-3759-11eb-8256-ec9d0f3f604f.png)
This widget has been unmounted, so the State no longer has a context (and should be considered defunct).

The last version without this problem is 0.53.
In 0.54+1, this problem is still there, env: flutter 1.24.0 (web)

**Comment by funwithflutter** [comment]
Sorry can you expand on this issue. Could you give example code of when this causes an issue.

**Comment by idootop** [comment]
> Sorry can you expand on this issue. Could you give example code of when this causes an issue.

Just the example code in this package, but run in flutter for web env.
With version 0.53, there's no problem.
