### ISSUE TITLE
snow effect

### ISSUE THREAD

**Issue by zhoulijun12315** [funwithflutter/flutter_confetti#37]
I want to achieve the effect of falling snow, but I can't customize the particle.

**Comment by mgav** [comment]
Not perfect, but you could set a very small maximumSize and limit color to only white

**Comment by funwithflutter** [comment]
There is now an optional `createParticlePath` argument that takes a function where you can return a custom `Path`. The example is updated. You should be able to create a snow path 👍 

Closed in #39
