### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by IchordeDionysos** [funwithflutter/flutter_confetti#40]
This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:confetti`.
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by IchordeDionysos** [comment]
Blocked by knezzz/RandomColor#11

**Comment by IchordeDionysos** [comment]
@funwithflutter Migration should be unblocked now :) 

`random_color` recently added support for null safety ☺️

**Comment by IchordeDionysos** [comment]
The new Dart version was just released 😍 
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by NarHakobyan** [comment]
> The new Dart version with null-safety was just released 😍
> [medium.com/dartlang/announcing-dart-2-12-499a6e689c87](https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87)

@IchordeDionysos you are so fast 😄

**Comment by IchordeDionysos** [comment]
@funwithflutter any plans to release a stable version with null-safety? ☺️ 
It's been almost a month now since the null-safe pre-release version

**Comment by ScottishRoss** [comment]
I have issues with null-safety with these dependencies: 
 - package:confetti
 - package:random_color
Any ideas on how I can get past that?

**Comment by NarHakobyan** [comment]
> I have issues with null-safety with these dependencies:
> 
> * package:confetti
> * package:random_color
>   Any ideas on how I can get past that?

@ScottishRoss use following versions.
```
random_color: 1.0.6-nullsafety
confetti: 0.6.0-nullsafety
```

**Comment by IchordeDionysos** [comment]
@funwithflutter the pre-release version is now published for more than a month.

Do you feel confident now to publish a stable version yet?
