### ISSUE TITLE
Confetti not appearing in Version ^0.6.0-nullsafety

### ISSUE THREAD

**Issue by aseemahuja** [funwithflutter/flutter_confetti#47]
Hi, I implemented Confetti before NullSafety and it was working fine. But when I upgraded it to NullSafety version, it stopped working. No error coming.

**Comment by funwithflutter** [comment]
Can you give me a bit more info please? Post some code that breaks it?

**Comment by Abacaxi-Nelson** [comment]
+1 just copy/paster example

**Comment by HayesGordon** [comment]
Closing this as it is probably no longer an issue in the later versions.
