### ISSUE TITLE
The library 'package:confetti/confetti.dart' is legacy, and should not be imported into a null safe library.

### ISSUE THREAD

**Issue by MetaBoy8** [funwithflutter/flutter_confetti#49]
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:confetti

- package:random_color

For solutions, see https://dart.dev/go/unsound-null-safety

**Comment by WinterSpringTiger** [comment]
![image](https://user-images.githubusercontent.com/86504841/127725496-b7f52c46-d6e8-469e-9088-ea55dd36efd4.png)

I have ran flutter pub add confetti and imported confetti.dart.
But I get the above issue.
Please help me.

**Comment by devj3ns** [comment]
Hey, when you have null safety enabled in your project (which is recommended) you also have to use the null safe version of the packages your project depends on.

Thus, import them like this (in your pubspec.yaml file):

```
confetti: ^0.6.0-nullsafety
random_color: ^1.0.6-nullsafety
```

**Comment by funwithflutter** [comment]
Closing this as there is a null-safe version now.
