### ISSUE TITLE
Performance is low on Android

### ISSUE THREAD

**Issue by penguru** [funwithflutter/flutter_confetti#50]
In many Android phones I tested, animation is quite slow

**Comment by funwithflutter** [comment]
Hey @penguru, at least for the time being it may be slow on older devices. I have some ideas to improve the performance in the future.

**Comment by cekrozl1** [comment]
Would you have any recommendations on how to optimise confetti animations? 
Something to add to the pages with confettis, or maybe something to avoid / remove?

https://user-images.githubusercontent.com/86661185/193251827-db79de15-b0a0-4527-9a32-191397280336.mov

**Comment by cekrozl1** [comment]
Hi ! 

A quick update on the performance issue. It has been identified and likely related to the [page transition](https://github.com/kalismeras61/flutter_page_transition/issues/76) widget. 

**The confettis have no performance issues after the page_transition is removed.**

**Comment by HayesGordon** [comment]
Hi @cekrozl1 thanks for sharing. Yes unfortunately if there are other complex operations/animations happening, then it may result in dropped frames.

In the latest release there will be big performance enhancements: https://github.com/funwithflutter/flutter_confetti/pull/76

In this release it will be more performant and it will also try to limit the number of confetti being created if there are missed frames. See the changelog for details.

That said, it's always recommended to test animations on the lowest supported device.

**Comment by HayesGordon** [comment]
Something we could add in the future is an optimized performance mode, and then subsequently disable some of the effects. For example, rotations.
