### ISSUE TITLE
Does it put out of screen?

### ISSUE THREAD

**Issue by aimsugita** [funwithflutter/flutter_confetti#6]
I can't put it out of screen.
I don't want to show the the particle emitter.

```
    return Align(
      alignment: Alignment.bottomCenter,
      child: ConfettiWidget(
          child: SizedBox(
              width: 0, height: SCREEN_SIZE + 10),
          confettiController: _confettiController,
          shouldLoop: true,
          blastDirection: pi / 2,
          maxBlastForce: 5,
          minBlastForce: 2,
          emissionFrequency: 0.05,
          numberOfParticles: 10,
          displayTarget: true,
      ),
    );
```
or
```
    return Align(
      alignment: Alignment.bottomCenter,
      child: Column(
        verticalDirection: VerticalDirection.up,
        children: [
          SizedBox(SCREEN_SIZE + 10),
          ConfettiWidget(
            confettiController: _confettiController,
            shouldLoop: true,
            blastDirection: pi / 2,
            maxBlastForce: 5,
            minBlastForce: 2,
            emissionFrequency: 0.05,
            numberOfParticles: 10,
            displayTarget: true,
          ),
        ],
      ),
    );
```

**Comment by aimsugita** [comment]
@funwithflutter 
Thank you for replying.

> You mean you do not want to show the little circle where the particles are emitting from?

No, I don't mean that.
I mean I want to put confetti nozzle in the out of screen.
Because of, I'd like to hide confetti crowding moment.

**Comment by funwithflutter** [comment]
Yes, you can do that. The widget is the same as any widget in Flutter, you just need to put the center point off screen. Maybe wrap it in a `transform.translate` and give it an Offset to be off-screen.

https://api.flutter.dev/flutter/widgets/Transform/Transform.translate.html

**Comment by aimsugita** [comment]
@funwithflutter Thank you for replying.
I could moved
