### ISSUE TITLE
Exception in Android builds

### ISSUE THREAD

**Issue by the100rabh** [funwithflutter/flutter_confetti#62]
I was trying this awesome widget. It works fine in chrome for me but errors out in Android builds. Following is the error I see and everything in the screen goes black. Not sure if this is enough for you to debug the issue. 

```
/home/the100rabh/.pub-cache/hosted/pub.dartlang.org/confetti-0.6.0/lib/src/confetti.dart:229:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/home/the100rabh/snap/flutter/common/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
```

**Comment by armandojimenez** [comment]
Any update on this?

**Comment by funwithflutter** [comment]
Flutter 3.0 made this non-nullable. So this is just a warning and nothing to worry about. But will be removed in the latest release (0.7). Closing this as the new release will be out soon.
