### ISSUE TITLE
 displayTarget

### ISSUE THREAD

**Issue by VimeshPolaris** [funwithflutter/flutter_confetti#63]
Hii Their, 
When I'm trying to use the following property ,
displayTarget: true,

The one widget was were showing that i can't remove.
Please help me out this:

![Screenshot 2022-05-03 at 3 59 08 PM](https://user-images.githubusercontent.com/95465974/166438929-11ef2c28-6f52-41c2-9d03-61b4014b039d.png)

How  can i remove that center widget ?

I want to use display target property but i can't use it.

**Comment by funwithflutter** [comment]
Seems like there is confusion with what the displayTarget is. When set to true it will show that centre widget to indicate the centre of the the ConfettiWidget canvas. Set it to false to not show.
