### ISSUE TITLE
Is there a way to control the speed and amount of confetti based on seconds instead of framerate?

### ISSUE THREAD

**Issue by edwardcahyadi** [funwithflutter/flutter_confetti#68]
I recently changed my phone display settings from 60hz to 120hz. I noticed that this caused more confetti to be produced and caused them to fall faster.

This is an issue because different users with different devices will have a different user experience.

Is there an easy way to base the speeds on actual time (seconds) instead on the device's framerate?

**Comment by acoutts** [comment]
I'm having the same issue - iphone 13 with promotion display.

**Comment by Eerey** [comment]
As documented, it is strongly tied to drawing a frame. Yes, you'd need to multiply it with the fps rate.
![image](https://user-images.githubusercontent.com/7249645/188180874-389b616b-da5d-46fc-88cd-afb8aa54e0e4.png)

**Comment by HayesGordon** [comment]
Hi, @edwardcahyadi, thanks for opening this issue, I'll look into this soon. It will likely be breaking changes and a rewrite of the underlying logic - I'll keep you updated here. It'll be something similar to this: https://en.wikipedia.org/wiki/Delta_timing

**Comment by HayesGordon** [comment]
Sorry that this took so long, but I have implemented a fix, and will release a new release after some additional changes. Please feel free to test out the `develop` branch in the meantime.
