### ISSUE TITLE
[feature request] Audio

### ISSUE THREAD

**Issue by cyb3rsalih** [funwithflutter/flutter_confetti#69]
Hi, I am using the plugin in my app for finish level animations. It works well 👍 I notice that just showing confetti is not exciting enough. You may add a parameter for play music from asset. Music starts to play syncronously with confetti.

Thanks.

**Comment by HayesGordon** [comment]
Hi, that's a good suggestion. But it's probably something that should be kept separate from this package. This will require adding additional assets and packages to the package. Someone can easily implement this themselves, in combination with this package. Closing this for now.
