### ISSUE TITLE
How can I define colors?

### ISSUE THREAD

**Issue by aimsugita** [funwithflutter/flutter_confetti#7]
It has many colors.
I'd like to define colors of confetti.

**Comment by funwithflutter** [comment]
I've been meaning to add this feature, thanks for bringing it up. I'll post here once the new version supports this.

**Comment by funwithflutter** [comment]
Okay. It is now possible to add a list of Colors to the `ConfettiWidget`. For example,

`
ConfettiWidget( confettiController: _controller, colors: [Colors.green, Colors.blue, Colors.pink],),
`

Enjoy.
