### ISSUE TITLE
Stop animation and hide confetti without to be off screen?

### ISSUE THREAD

**Issue by Gilianp** [funwithflutter/flutter_confetti#73]
When I perform a single shot, I have to wait for all the particles to leave the screen for the animation to end. I wish I could hide the particles before they leave the screen.
How to stop the animation and hide the particles without having to wait for all of them to be off screen?

**Comment by cbatson** [comment]
@Gilianp Can you not just rebuild your parent widget (based on a Timer, perhaps) without the `ConfettiWidget`?

**Comment by HayesGordon** [comment]
Hey @Gilianp, you can now do: `confettiController.stop(clearAllParticles: true);`

This is currently in the **develop** branch and will land on Pub soon.
