### ISSUE TITLE
Crashes on Android with Flutter 3.7.0

### ISSUE THREAD

**Issue by chen-fishbein** [funwithflutter/flutter_confetti#78]
Calling 
_controller.play();

Crashes the app with the below cryptic native errors:

F/libc    (30185): Fatal signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x712a3eda14 in tid 30253 (1.ui), pid 30185
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
....

**Comment by knnkrt** [comment]
Same bug.

**Comment by AphroditePeng** [comment]
Same bug on iOS with Flutter 3.7.0

**Comment by yanncabral** [comment]
Same here.

**Comment by LuckyBulgur** [comment]
Same bug on iOS 16 with Flutter 3.7.0.

**Comment by davestimpert** [comment]
yep this happens even in the example app in this repo

**Comment by starshipcoder** [comment]
Same problem

**Comment by DanhTran0312** [comment]
I have this problem on IOS 16.2 also

**Comment by hlarchi** [comment]
same problem on both iOS and Android with Flutter 3.7.0

**Comment by armandojimenez** [comment]
Any fix for this? crashes on both android and ios

**Comment by HayesGordon** [comment]
Hey all! Please see original issue here https://github.com/funwithflutter/flutter_confetti/issues/70

The fix has landed in Master, please confirm on your respective machines/devices.

Go upvote here for a path to stable: https://github.com/flutter/flutter/issues/118559#issuecomment-1404770385

Don't know how long it'll take for the fix to land on stable

**Comment by Gilianp** [comment]
Same here tested in Android 7, 9 and 11 after Flutter 3.7.0

**Comment by WieFel** [comment]
+1

**Comment by liorboyango** [comment]
Crashes also on MacOS with Flutter 3.7.0

**Comment by colbycornish** [comment]
Crashes on both mac and android with Flutter 3.7.0 for me

**Comment by chituanh** [comment]
+1

**Comment by Huy-Thai** [comment]
Crashes on mac and windows with Flutter 3.7.0 for me

**Comment by FlorianFlatscher** [comment]
When can I expect the fix getting merged into stable? Don't get me wrong, but confettis are kinda important for my application :/

**Comment by HayesGordon** [comment]
Soon hopefully. In the meantime you can use a different branch of Flutter. But seems like it's ready for a cherry pick: https://github.com/dart-lang/sdk/issues/51147

**Comment by egonbeermat** [comment]
Looks like the fix made it into the release 3.7.2 today. Release notes state, and testing confirms, this issue has gone away for me.

**Comment by xaatw0** [comment]
Thank you, [egonbeermat](https://github.com/egonbeermat)! You are right. It works with 3.7.2.

**Comment by HayesGordon** [comment]
That's great! I'm closing this issue for now then. If anyone experiences issues again, please re-open.
