### ISSUE TITLE
Changing confetti size option

### ISSUE THREAD

**Issue by aimsugita** [funwithflutter/flutter_confetti#8]
Hello.
I want the option for changing the size of confetti.

**Comment by funwithflutter** [comment]
Hi, good idea! I will add this in a future update.

**Comment by funwithflutter** [comment]
This feature has been added. Please give it a test and let me know. You will see an optional `minimumSize` and `maximumSize` property that can be set on the `ConfettiWidget` to control the size of the confetti.
