### ISSUE TITLE
iOS version crashing in Debug Mode

### ISSUE THREAD

**Issue by jrmarkham** [funwithflutter/flutter_confetti#82]
Flutter Confetti starting getting crashing in debug mode on simulators and hardware devices. Not a show-stopper for me just a heads up.

**Comment by egonbeermat** [comment]
Which Flutter version are you using? There was an issue in 3.7.0 update that causes confetti to crash in debug mode, devices or emulators. It was resolved in 3.7.2

**Comment by HayesGordon** [comment]
Yeah this should be resolved in 3.7.2 of Flutter. Closing this for now, but @jrmarkham please reopen if upgrading does not solve it for you. Thanks for reporting by the way.

**Comment by jrmarkham** [comment]
Yup working 3.7.4. Thanks for the quick response.
