### ISSUE TITLE
[QUESTION] Project outdated

### ISSUE THREAD

**Issue by vtisnado** [funwithflutter/flutter_confetti#86]
Hello everyone,

I would like to bring to your attention that the project hasn't been updated in more than 12 months, and the most recent stable version was released in May 2022. I'm curious if there are any plans to continue working on the project, or if I could help with its development in any way.

Thank you for your hard work on this project.

**Comment by vtisnado** [comment]
Hey @HayesGordon any plan to update this project?

**Comment by echogit** [comment]
Also wondering if someone plans on maintaining or if there is any other implementation.

**Comment by HayesGordon** [comment]
Updated! Sorry about the long pause
