### ISSUE TITLE
Release `develop` branch improvements

### ISSUE THREAD

**Issue by absar** [funwithflutter/flutter_confetti#97]
Hi @HayesGordon thank you for this package.
I see you have done many improvements in `develop` branch, specially `delta time` without which particle speed and quantity is not consistent on different `fps` devices, would be nice if you release the changes and maybe with updated dependencies and wider dart lang version constraints e.g. `sdk: ">=2.17.0 <4.0.0"` instead of `sdk: ">=2.17.0 <3.0.0"`

**Comment by HayesGordon** [comment]
I'll yolo merge it! And get out a release 😅

**Comment by HayesGordon** [comment]
Don't remember what I did, but I trust old me did it for a reason

**Comment by HayesGordon** [comment]
Published 0.8.0. Let me know how it works for you.

**Comment by absar** [comment]
Thank you for the prompt response. Will definitely test it.

**Comment by absar** [comment]
@HayesGordon unfortunately v0.8 crashes when confetti is on a dialog. Please check: https://github.com/funwithflutter/flutter_confetti/issues/99
